# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(333, 207)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setMinimumSize(QtCore.QSize(75, 23))
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.inputLogin = QtWidgets.QLineEdit(Form)
        self.inputLogin.setMinimumSize(QtCore.QSize(133, 20))
        self.inputLogin.setObjectName("inputLogin")
        self.gridLayout.addWidget(self.inputLogin, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.inputPassword = QtWidgets.QLineEdit(Form)
        self.inputPassword.setMinimumSize(QtCore.QSize(133, 20))
        self.inputPassword.setObjectName("inputPassword")
        self.gridLayout.addWidget(self.inputPassword, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.loginButton.clicked.connect(self.inputLogin.copy)
        self.loginButton.clicked.connect(self.inputPassword.copy)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginButton.setText(_translate("Form", "Войти"))
        self.inputLogin.setToolTip(_translate("Form", "<html><head/><body><p>Login</p><p><br/></p></body></html>"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))

app = QtWidgets.QApplication(sys.argv)
ex = Ui_Form()
ex.setupUi()
