# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainroot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 421)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(True)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setAccessibleName("")
        self.label.setAccessibleDescription("")
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Console = QtWidgets.QScrollArea(Dialog)
        self.Console.setWidgetResizable(True)
        self.Console.setObjectName("Console")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 370))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.console_out = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.console_out.setGeometry(QtCore.QRect(0, 0, 301, 371))
        self.console_out.setObjectName("console_out")
        self.Console.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.Console, 1, 0, 2, 1)
        self.SongList = QtWidgets.QListWidget(Dialog)
        self.SongList.setObjectName("SongList")
        self.gridLayout.addWidget(self.SongList, 1, 1, 1, 1)
        self.buttons = QtWidgets.QDialogButtonBox(Dialog)
        self.buttons.setMouseTracking(False)
        self.buttons.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttons.setCenterButtons(False)
        self.buttons.setObjectName("buttons")
        self.gridLayout.addWidget(self.buttons, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttons.accepted.connect(Dialog.accept)
        self.buttons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "VK music downloader"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Console</span></p></body></html>"))
